name = "artesa-nfc"
main = "src/index.js"
compatibility_date = "2026-01-01"

[assets]
directory = "public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "artesanfc-db"
database_id = "c1feb5a1-0fca-4d4b-82bd-76e5bc10527f"
