"""create certificate table

Revision ID: 8c2f9a74e447
Revises: 9229b1f0f11c
Create Date: 2026-09-18 13:48:51.576293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8c2f9a74e447'
down_revision: Union[str, None] = '9229b1f0f11c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('piece_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=True),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'revoked', name='certificate_status'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('authenticity_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'draft' AND token_hash IS NULL) OR (status IN ('active', 'revoked') AND token_hash IS NOT NULL)", name='ck_certificate_token_hash_matches_status'),
    sa.CheckConstraint("(status = 'revoked' AND revoked_at IS NOT NULL) OR (status != 'revoked' AND revoked_at IS NULL)", name='ck_certificate_revoked_at_matches_status'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_certificate_piece_id'), 'certificate', ['piece_id'], unique=False)
    op.create_index('ix_certificate_piece_id_status', 'certificate', ['piece_id', 'status'], unique=False)
    op.create_index(op.f('ix_certificate_status'), 'certificate', ['status'], unique=False)
    op.create_index('uq_certificate_one_active_per_piece', 'certificate', ['piece_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_certificate_one_active_per_piece', table_name='certificate', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_certificate_status'), table_name='certificate')
    op.drop_index('ix_certificate_piece_id_status', table_name='certificate')
    op.drop_index(op.f('ix_certificate_piece_id'), table_name='certificate')
    op.drop_table('certificate')
    # ### end Alembic commands ###
    # Autogenerate does not emit DROP TYPE for Postgres native enums; without
    # this, a downgrade-then-upgrade cycle fails with "type already exists"
    # (same reasoning as 9229b1f0f11c).
    postgresql.ENUM(name='certificate_status').drop(op.get_bind(), checkfirst=True)
