"""create artisan piece media_asset tables

Revision ID: 9229b1f0f11c
Revises: 
Create Date: 2026-09-17 16:21:26.095069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9229b1f0f11c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artisan',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('artistic_name', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('municipality', sa.Text(), nullable=True),
    sa.Column('state', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('languages_public', sa.Boolean(), nullable=False),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('techniques', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('public_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('publication_status', sa.Enum('draft', 'published', 'archived', name='publication_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_artisan_publication_status'), 'artisan', ['publication_status'], unique=False)
    op.create_table('piece',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('public_code', sa.Text(), nullable=False),
    sa.Column('artisan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('history', sa.Text(), nullable=True),
    sa.Column('technique', sa.Text(), nullable=True),
    sa.Column('materials', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('origin', sa.Text(), nullable=True),
    sa.Column('creation_year', sa.SmallInteger(), nullable=True),
    sa.Column('creation_date', sa.Date(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('visual_theme', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('availability_status', sa.Enum('available', 'reserved', 'exhibited', 'archived', name='piece_availability_status'), nullable=False),
    sa.Column('publication_status', sa.Enum('draft', 'published', 'archived', name='publication_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_code'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_piece_artisan_id'), 'piece', ['artisan_id'], unique=False)
    op.create_index(op.f('ix_piece_publication_status'), 'piece', ['publication_status'], unique=False)
    op.create_table('media_asset',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('artisan_id', sa.UUID(), nullable=True),
    sa.Column('piece_id', sa.UUID(), nullable=True),
    sa.Column('media_type', sa.Enum('image', 'video', 'model_3d', 'sequence_360', name='media_asset_type'), nullable=False),
    sa.Column('role', sa.Enum('hero', 'gallery', 'detail', 'process', 'portrait', 'document', 'model_3d', 'sequence_360', name='media_asset_role'), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('alt_text', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('format_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='media_asset_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("media_type != 'image' OR alt_text IS NOT NULL", name='ck_media_asset_alt_text_required_for_image'),
    sa.CheckConstraint('num_nonnulls(artisan_id, piece_id) <= 1', name='ck_media_asset_single_owner'),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_asset_artisan_id'), 'media_asset', ['artisan_id'], unique=False)
    op.create_index('ix_media_asset_owner_role_position', 'media_asset', ['artisan_id', 'piece_id', 'role', 'position'], unique=False)
    op.create_index(op.f('ix_media_asset_piece_id'), 'media_asset', ['piece_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_asset_piece_id'), table_name='media_asset')
    op.drop_index('ix_media_asset_owner_role_position', table_name='media_asset')
    op.drop_index(op.f('ix_media_asset_artisan_id'), table_name='media_asset')
    op.drop_table('media_asset')
    op.drop_index(op.f('ix_piece_publication_status'), table_name='piece')
    op.drop_index(op.f('ix_piece_artisan_id'), table_name='piece')
    op.drop_table('piece')
    op.drop_index(op.f('ix_artisan_publication_status'), table_name='artisan')
    op.drop_table('artisan')
    # ### end Alembic commands ###
    # Autogenerate does not emit DROP TYPE for Postgres native enums; without
    # this, a downgrade-then-upgrade cycle fails with "type already exists".
    postgresql.ENUM(name='media_asset_type').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='media_asset_role').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='media_asset_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='piece_availability_status').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='publication_status').drop(op.get_bind(), checkfirst=True)
