"""create nfc_tag table

Revision ID: 9b8bb430770d
Revises: 8c2f9a74e447
Create Date: 2026-09-18 15:18:27.645322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '9b8bb430770d'
down_revision: Union[str, None] = '8c2f9a74e447'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfc_tag',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('piece_id', sa.UUID(), nullable=True),
    sa.Column('chip_model', sa.Text(), nullable=False),
    sa.Column('frequency', sa.Text(), nullable=True),
    sa.Column('protocol', sa.Text(), nullable=True),
    sa.Column('physical_uid', sa.Text(), nullable=True),
    sa.Column('programmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('available', 'programmed', 'locked', 'replaced', 'retired', name='nfc_tag_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("locked_at IS NULL OR status = 'locked'", name='ck_nfc_tag_locked_at_matches_status'),
    sa.CheckConstraint("status NOT IN ('programmed', 'locked') OR piece_id IS NOT NULL", name='ck_nfc_tag_assignment_requires_piece'),
    sa.ForeignKeyConstraint(['piece_id'], ['piece.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('physical_uid')
    )
    op.create_index(op.f('ix_nfc_tag_piece_id'), 'nfc_tag', ['piece_id'], unique=False)
    op.create_index('uq_nfc_tag_one_active_per_piece', 'nfc_tag', ['piece_id'], unique=True, postgresql_where=sa.text("status IN ('programmed', 'locked')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_nfc_tag_one_active_per_piece', table_name='nfc_tag', postgresql_where=sa.text("status IN ('programmed', 'locked')"))
    op.drop_index(op.f('ix_nfc_tag_piece_id'), table_name='nfc_tag')
    op.drop_table('nfc_tag')
    # ### end Alembic commands ###
    # Autogenerate does not emit DROP TYPE for Postgres native enums; without
    # this, a downgrade-then-upgrade cycle fails with "type already exists"
    # (same reasoning as 9229b1f0f11c / 8c2f9a74e447).
    postgresql.ENUM(name='nfc_tag_status').drop(op.get_bind(), checkfirst=True)
