"""Fixtures and fakes for the N-08 ops tests.

``make_repo`` builds a throw-away git repository with a *synthetic* backend
tree (never the real one) and a real ``origin/main`` remote-tracking ref, so
the builder's git-object and reachability logic is exercised for real.

``World`` simulates the machine the deploy tool acts on: which release the
"service" is serving, the database revision, what ``pg_dump`` produces. The
tool itself is the real code; only process/network/systemd edges are faked.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timedelta, timezone
from pathlib import Path

import artesa_deploy as ad
import build_release as br
import deploy_layout as dl
import release_artifact as ra
import release_common as rc
import release_probe as rp

NOW = datetime(2026, 9, 21, 3, 0, 0, tzinfo=timezone.utc)
CANARY_PASSWORD = "Sup3r-S3cret-Canary-Pw"  # deliberately distinctive
CANARY_USER = "canary_db_operator"
DATABASE_URL = f"postgresql://{CANARY_USER}:{CANARY_PASSWORD}@127.0.0.1:5433/artesa_prod"
CANARY_OTHER = "CANARY-api-key-0123456789"

LOCK = """#
# This file is autogenerated by pip-compile with Python 3.14
# by the following command:
#
#    pip-compile --generate-hashes --output-file=requirements-prod.lock requirements-prod.in
#
fastapi==0.115.6 \\
    --hash=sha256:{h1} \\
    --hash=sha256:{h2}
    # via -r requirements-prod.in
sqlalchemy==2.0.44 \\
    --hash=sha256:{h1}
    # via -r requirements-prod.in
uvicorn==0.34.0 \\
    --hash=sha256:{h2}
    # via -r requirements-prod.in
""".format(h1="a" * 64, h2="b" * 64)

LEDGER = {
    "schema_version": 1,
    "revisions": {
        "aaa111": {"class": "baseline", "note": "initial"},
        "bbb222": {"class": "additive", "note": "adds a table"},
    },
}


def migration(rev: str, down: str | None) -> str:
    return f'revision = "{rev}"\ndown_revision = {down!r}\n\ndef upgrade():\n    pass\n'


BASE_FILES: dict[str, str] = {
    "backend/app/__init__.py": "",
    "backend/app/main.py": "_RESOLVE_MAX_BODY_BYTES = 1024\n",
    "backend/app/core/__init__.py": "",
    "backend/app/core/config.py": "class Settings:\n    @property\n    def docs_enabled(self):\n        return False\n",
    "backend/app/core/db_safety.py": "SAFE = True\n",
    "backend/alembic.ini": "[alembic]\nscript_location = alembic\n",
    "backend/alembic/env.py": "# env\n",
    "backend/alembic/versions/aaa111_first.py": migration("aaa111", None),
    "backend/alembic/versions/bbb222_second.py": migration("bbb222", "aaa111"),
    "backend/ops/migration-classes.json": json.dumps(LEDGER),
    "backend/ops/release_probe.py": "# placeholder\n",
    "backend/requirements-prod.lock": LOCK,
    # tracked but never packaged
    "backend/tests/test_something.py": "def test_x():\n    pass\n",
    "backend/.env.example": "APP_ENV=local\n",
    "backend/README.md": "# backend\n",
    "docs/DECISIONS.md": "# decisions\n",
}


def run_git(repo: Path, *args: str) -> str:
    env = {**os.environ, "GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@example.com",
           "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@example.com",
           "GIT_AUTHOR_DATE": "2026-09-20T12:00:00Z", "GIT_COMMITTER_DATE": "2026-09-20T12:00:00Z"}
    return subprocess.run(["git", "-C", str(repo), "-c", "commit.gpgsign=false", "-c", "tag.gpgsign=false", "-c", "core.hooksPath=/dev/null", *args],
                          check=True, capture_output=True, text=True, env=env).stdout.strip()


def write_files(repo: Path, files: dict[str, str]) -> None:
    for name, content in files.items():
        target = repo / name
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content)


def make_repo(tmp_path: Path, files: dict[str, str] | None = None, *, with_origin: bool = True) -> Path:
    repo = tmp_path / "repo"
    repo.mkdir(parents=True)
    run_git(repo, "init", "-q", "-b", "main")
    write_files(repo, {**BASE_FILES, **(files or {})})
    run_git(repo, "add", "-A")
    run_git(repo, "commit", "-q", "-m", "initial")
    if with_origin:
        origin = tmp_path / "origin.git"
        subprocess.run(["git", "init", "-q", "--bare", "-b", "main", str(origin)], check=True)
        run_git(repo, "remote", "add", "origin", str(origin))
        run_git(repo, "push", "-q", "origin", "main")
        run_git(repo, "fetch", "-q", "origin")
    return repo


def commit(repo: Path, files: dict[str, str], message: str = "change", *, push: bool = False) -> str:
    write_files(repo, files)
    run_git(repo, "add", "-A")
    run_git(repo, "commit", "-q", "-m", message)
    if push:
        run_git(repo, "push", "-q", "origin", "main")
        run_git(repo, "fetch", "-q", "origin")
    return run_git(repo, "rev-parse", "HEAD")


def build(repo: Path, out: Path, *, ref: str = "origin/main", rehearsal: bool = False, when: datetime = NOW) -> br.BuildResult:
    return br.build_release(repo, out, ref=ref, rehearsal=rehearsal, release_time=when)


# --- tar helpers (to craft hostile archives) -----------------------------------------

def rewrite_tar(artifact: Path, mutate, *, fix_sidecar: bool = True) -> Path:
    """Read a built artifact's members, let ``mutate(dict name->bytes)`` edit
    them, write a new tar next to it with a *valid* sidecar for the new bytes
    (so only the layers under test can object)."""
    import gzip, io, tarfile

    members: dict[str, bytes] = {}
    with tarfile.open(artifact, "r:gz") as tar:
        for m in tar:
            members[m.name] = tar.extractfile(m).read()
    mutate(members)
    out = artifact.with_name(artifact.name.replace(".tar.gz", "-x.tar.gz"))
    out = artifact  # keep the canonical name: the id in the file name must still match
    raw = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=raw, mtime=0) as gz:
        with tarfile.open(fileobj=gz, mode="w", format=tarfile.USTAR_FORMAT) as tar:
            for name in sorted(members):
                info = tarfile.TarInfo(name)
                info.size = len(members[name]); info.mode = 0o644
                tar.addfile(info, io.BytesIO(members[name]))
    out.write_bytes(raw.getvalue())
    if fix_sidecar:
        out.with_name(out.name + ".sha256").write_text(f"{rc.sha256_bytes(raw.getvalue())}  {out.name}\n")
    return out


# --- a fake machine --------------------------------------------------------------------

def compliant_fetch(docs_status: int = 404):
    """Behaves like the real API for the smoke checks."""
    def fetch(port, method, path, *, headers=None, body=None, timeout=5.0, host="127.0.0.1"):
        headers = headers or {}
        j = lambda obj, status=200, extra=None: rp.HttpResult(status, {"content-type": "application/json", **(extra or {})}, json.dumps(obj).encode())
        if path == "/health":
            return j({"status": "ok", "database": "connected"})
        if path == "/api/v1/artisans":
            extra = {}
            if headers.get("Origin") == rc.PRODUCTION_FRONTEND_ORIGIN:
                extra["access-control-allow-origin"] = rc.PRODUCTION_FRONTEND_ORIGIN
            return j({"data": [], "meta": {"total": 0}}, extra=extra)
        if path == "/api/v1/certificates/resolve" and method == "POST":
            if body and len(body) > 1024:
                return j({"error": {"code": "payload_too_large"}}, 413)
            if body == b"{}":
                return j({"error": {"code": "validation_error"}}, 422)
            return j({"authenticity": {"status": "unavailable"}}, extra={"cache-control": "no-store"})
        if path in ("/docs", "/redoc", "/openapi.json"):
            return rp.HttpResult(docs_status, {}, b"")
        return j({"error": {"code": "not_found"}}, 404)
    return fetch


@dataclass
class World:
    """State shared by the fake runner, service, port inspector and HTTP."""
    root: Path
    db_revision: str | None = "bbb222"
    row_counts: dict = field(default_factory=lambda: {"artisan": 2, "piece": 5})
    serving: str | None = None          # release id the "service" is running
    broken: set = field(default_factory=set)   # release ids that fail after restart
    alien_on_port: bool = False
    restarts: int = 0
    argv_log: list = field(default_factory=list)
    envs_log: list = field(default_factory=list)
    migrate_ok: bool = True
    pg_dump_ok: bool = True
    pg_dump_empty: bool = False
    pg_major: int = 18
    initdb_major: int | None = 18        # None: no server binaries (initdb missing)
    server_version_num: int = 180006
    calls: list = field(default_factory=list)
    # the disposable restore database: None until created, then {"rev", "rows"}
    scratch: dict | None = None
    scratch_created: int = 0
    scratch_destroyed: int = 0
    restore_ok: bool = True
    restore_drops_rows: bool = False     # restored copy loses rows (count mismatch)
    scratch_migrate_ok: bool = True      # alembic upgrade on the restored copy
    extra_installed: dict = field(default_factory=dict)   # venv drift: name -> version

    def state_hash(self) -> str:
        """Fingerprint of everything a dry-run must not change."""
        parts = []
        for path in sorted(self.root.rglob("*")):
            rel = path.relative_to(self.root)
            if path.is_symlink():
                parts.append(f"L {rel} {os.readlink(path)}")
            elif path.is_file():
                parts.append(f"F {rel} {rc.sha256_file(str(path))}")
            else:
                parts.append(f"D {rel}")
        parts.append(f"db={self.db_revision}:{sorted(self.row_counts.items())} restarts={self.restarts}")
        return rc.sha256_bytes("\n".join(parts).encode())


class FakeRunner(rp.Runner):
    """A Runner that never spawns anything. It still enforces the real argv
    secret guard, records every argv/env, and answers from the World."""

    def __init__(self, world: World, guard: rp.SecretGuard | None = None) -> None:
        super().__init__(guard)
        self.world = world

    def run(self, argv, *, env=None, cwd=None, timeout=120, inherit_tty=False):
        argv = [str(a) for a in argv]
        self.guard.check_argv(argv)
        w = self.world
        w.argv_log.append(argv)
        w.envs_log.append(dict(env or {}))
        joined = " ".join(argv)
        name = os.path.basename(argv[0])
        for handler in getattr(self, "handlers", []):
            answer = handler(argv, dict(env or {}), cwd)
            if answer is not None:
                return answer
        if name == "systemctl":
            return rp.RunResult(0, "ActiveState=active\nSubState=running\nNRestarts=0\n"
                                   f"WorkingDirectory={w.root / 'current'}\n"
                                   f"ExecStart={{ path={w.root / 'current' / 'venv' / 'bin' / 'python'} ; argv[]=x ; }}\n")
        scratch_url = "artesa_restore_test_" in (env or {}).get("DATABASE_URL", "")
        if "downgrade" in joined:
            raise AssertionError("alembic downgrade must never be run")
        if argv[-1] == "db-state":
            if scratch_url:
                sc = w.scratch or {"rev": None, "rows": {}}
                return rp.RunResult(0, json.dumps({"server_version_num": w.server_version_num,
                                                   "alembic_versions": [sc["rev"]] if sc["rev"] else [], "row_counts": sc["rows"]}))
            if w.db_revision == "__unreachable__":
                return rp.RunResult(23, "", "error: database probe failed (OperationalError)")
            return rp.RunResult(0, json.dumps({"server_version_num": w.server_version_num,
                                               "alembic_versions": [w.db_revision] if w.db_revision else [],
                                               "row_counts": w.row_counts}))
        if "alembic" in argv and "upgrade" in argv:
            head = json.loads(Path(cwd, "RELEASE.json").read_text())["alembic"]["head"]
            if scratch_url:
                if not w.scratch_migrate_ok:
                    return rp.RunResult(1, "", "sqlalchemy.exc.ProgrammingError: boom on copy")
                w.scratch["rev"] = head
                return rp.RunResult(0)
            if not w.migrate_ok:
                return rp.RunResult(1, "", "sqlalchemy.exc.ProgrammingError: boom")
            w.db_revision = head
            return rp.RunResult(0)
        if "pip" in argv and "list" in argv:
            release_dir = Path(argv[0]).parents[2]
            pins = rc.parse_lock((release_dir / rc.LOCK_PATH).read_text())
            pins.update(w.extra_installed)
            return rp.RunResult(0, json.dumps([{"name": n, "version": v} for n, v in [*pins.items(), ("pip", "25.0")]]))
        if name == "initdb" and "--version" in argv:
            if w.initdb_major is None:
                return rp.RunResult(127, "", "command not found: initdb")
            return rp.RunResult(0, f"initdb (PostgreSQL) {w.initdb_major}.6\n")
        if name == "initdb":
            assert not any("pw" == a or a.startswith("--pwfile=") and not Path(a.split("=", 1)[1]).exists() for a in argv)
            Path(argv[argv.index("-D") + 1]).mkdir()
            return rp.RunResult(0)
        if name == "pg_ctl":
            if argv[-1] == "stop" and w.scratch is not None:  # the whole throw-away cluster goes away
                w.scratch_destroyed += 1
                w.scratch = None
            return rp.RunResult(0)
        if name == "createdb":
            w.scratch_created += 1
            w.scratch = {"rev": None, "rows": {}}
            return rp.RunResult(0)
        if name == "dropdb":
            w.scratch_destroyed += 1
            w.scratch = None
            return rp.RunResult(0)
        if name == "pg_dump" and "--version" in argv:
            return rp.RunResult(0, f"pg_dump (PostgreSQL) {w.pg_major}.6 (Debian)\n")
        if name == "pg_dump":
            if not w.pg_dump_ok:
                return rp.RunResult(1, "", "pg_dump: error: connection to server failed")
            target = next(a.split("=", 1)[1] for a in argv if a.startswith("--file="))
            Path(target).write_bytes(b"" if w.pg_dump_empty else b"PGDMP-fake-archive")
            return rp.RunResult(0)
        if name == "pg_restore" and "--list" in argv:
            if Path(argv[-1]).read_bytes()[:5] != b"PGDMP":
                return rp.RunResult(1, "", "pg_restore: error: input file does not appear to be a valid archive")
            toc = "".join(f"{i}; 1259 {16000 + i} TABLE public {t} owner\n" for i, t in enumerate(["alembic_version", *w.row_counts]))
            return rp.RunResult(0, toc)
        if name == "pg_restore":
            if not w.restore_ok:
                return rp.RunResult(1, "", "pg_restore: error: could not execute query")
            rows = dict(w.row_counts)
            if w.restore_drops_rows:
                rows[next(iter(rows))] -= 1
            w.scratch = {"rev": w.db_revision, "rows": rows}
            return rp.RunResult(0)
        return rp.RunResult(0)


class FakeService:
    def __init__(self, world: World) -> None:
        self.world = world

    def restart(self) -> None:
        w = self.world
        w.restarts += 1
        try:
            w.serving = os.path.basename(os.path.realpath(w.root / "current"))
        except OSError:
            w.serving = None

    def info(self) -> dl.ServiceInfo:
        w = self.world
        return dl.ServiceInfo(True, "active", "running", 0, str(w.root / "current"), str(w.root / "current" / "venv" / "bin" / "python"))


def make_port_state(world: World):
    def port_state(port, expected_cwd, proc="/proc"):
        w = world
        if w.alien_on_port:
            return rp.PortState("alien", f"port {port} is held by pid 4242 (cwd /srv/other), not by the expected release", 4242)
        if w.serving is None or w.serving in w.broken:
            return rp.PortState("free", f"nothing listens on port {port}")
        if expected_cwd is None:
            return rp.PortState("alien", "unexpected listener")
        if os.path.basename(os.path.realpath(expected_cwd)) == w.serving:
            return rp.PortState("expected", f"port {port} is held by the expected release", 1)
        return rp.PortState("alien", f"port {port} is held by pid 1 (cwd elsewhere), not by the expected release", 1)
    return port_state


def make_fetch(world: World):
    good = compliant_fetch()
    def fetch(port, method, path, **kw):
        if world.serving is None or world.serving in world.broken:
            raise ConnectionRefusedError("down")
        return good(port, method, path, **kw)
    return fetch


def make_candidate(world: World, *, ok: bool = True):
    def candidate(*, release_dir, env, port, log_path, release, guard, fetch=None, **kw):
        world.calls.append(("candidate", os.path.basename(release_dir), port))
        Path(log_path).write_text("INFO candidate ok\n")
        os.chmod(log_path, 0o600)
        checks = [rp.Check("candidate starts and answers /health", ok, "")]
        return rp.CandidateReport(ok, checks, str(log_path), True, ok)
    return candidate


def write_env(root: Path, *, mode: int = 0o600, extra: str = "", url: str = DATABASE_URL, app_env: str = "production", debug: str = "False") -> Path:
    shared = root / "shared"
    shared.mkdir(parents=True, exist_ok=True)
    env = shared / ".env"
    env.write_text(
        f"APP_ENV={app_env}\nDATABASE_URL={url}\nDEBUG={debug}\n"
        f"CORS_ALLOWED_ORIGINS=https://artesanfc.com,https://www.artesanfc.com\n"
        f"CLOUDFLARE_API_TOKEN={CANARY_OTHER}\nSECRET_KEY=another-secret-value-123\n{extra}"
    )
    os.chmod(env, mode)
    return env


def install_release(root: Path, artifact_path: Path, *, prepared: bool = True) -> str:
    """Materialize a built artifact as releases/<id> exactly as ``prepare``
    would, minus pip: a stub venv and the .prepared marker."""
    verified = ra.verify_artifact(artifact_path)
    rid = verified.release_id
    dest = root / "releases" / rid
    (root / "releases").mkdir(parents=True, exist_ok=True)
    ra.extract_artifact(verified, dest)
    if prepared:
        (dest / "venv" / "bin").mkdir(parents=True)
        (dest / "venv" / "bin" / "python").write_text("#!/bin/sh\n")
        (dest / "venv" / "pyvenv.cfg").write_text("home = /usr/bin\n")
        dl.write_prepared(dest, {
            "schema_version": 1, "release_id": rid, "prepared_at": "2026-09-21T03:00:00Z", "tool_version": rc.TOOL_VERSION,
            "python": "3.14.4", "lockfile_sha256": verified.release["deps"]["lockfile_sha256"],
            "release_json_sha256": rc.sha256_file(str(dest / "RELEASE.json")), "content_sha256": verified.release["artifact"]["content_sha256"],
            "archive_sha256": verified.archive_sha256,
        })
    return rid


def link(root: Path, name: str, rid: str) -> None:
    dl.atomic_symlink(dl.Layout(root), root / name, rid)


class Sink:
    def __init__(self) -> None:
        self.lines: list[str] = []
    def __call__(self, text: str = "") -> None:
        self.lines.append(text)
    @property
    def text(self) -> str:
        return "\n".join(self.lines)


def make_ctx(world: World, sink: Sink, *, tty: bool = True, answers=None, candidate_ok: bool = True,
             public_ok: bool = True, clock=lambda: NOW) -> ad.Context:
    guard = rp.SecretGuard()
    answers = list(answers or [])
    ctx = ad.Context(
        root=world.root, rehearsal=True, prod_port=18000, candidate_port=18001,
        runner=FakeRunner(world, guard), service=FakeService(world),
        is_tty=lambda: tty, prompt=lambda msg: answers.pop(0) if answers else "",
        clock=clock, sleep=lambda s: None, out=sink, fetch=make_fetch(world),
        port_state=make_port_state(world), candidate=make_candidate(world, ok=candidate_ok),
        public_check=(lambda url: (public_ok, "status 200" if public_ok else "status 530")),
        health_timeout=0.0,
    )
    return ctx


# --- a whole deployment scenario ---------------------------------------------------------------------

class Scenario:
    """Root + repo + World + a ctx factory. ``release()`` commits a change,
    builds a real artifact from it and installs it as a prepared release."""

    def __init__(self, tmp_path: Path) -> None:
        self.tmp = tmp_path
        self.root = tmp_path / "artesa-nfc"
        for d in ("bin", "incoming", "releases", "shared/backups", "shared/state", "shared/deploys"):
            (self.root / d).mkdir(parents=True, exist_ok=True)
        os.chmod(self.root / "shared", 0o700)
        write_env(self.root)
        self.repo = make_repo(tmp_path)
        self.world = World(self.root)
        self.sink = Sink()
        self._n = 0
        self.ids: dict[str, str] = {}
        self.artifacts: dict[str, Path] = {}

    def release(self, name: str, files: dict[str, str] | None = None, *, prepared: bool = True, channel_rehearsal: bool = True) -> str:
        self._n += 1
        commit(self.repo, files or {f"backend/app/rev_{self._n}.py": f"N = {self._n}\n"}, f"release {name}")
        result = build(self.repo, self.root / "incoming", ref="HEAD", rehearsal=channel_rehearsal, when=NOW + timedelta(minutes=self._n))
        self.artifacts[name] = result.artifact
        rid = install_release(self.root, result.artifact, prepared=prepared)
        self.ids[name] = rid
        return rid

    def activate(self, current: str, previous: str | None = None) -> None:
        link(self.root, "current", self.ids[current])
        if previous:
            link(self.root, "previous", self.ids[previous])
        self.world.serving = self.ids[current]

    def ctx(self, **kw) -> ad.Context:
        self.sink = Sink()
        return make_ctx(self.world, self.sink, **kw)

    def run(self, argv: list[str], **kw) -> int:
        ctx = self.ctx(**kw)
        self.last_ctx = ctx
        return ad.main(["--root", str(self.root), "--rehearsal", "--prod-port", "18000", "--candidate-port", "18001", *argv], ctx)

    def current(self) -> str | None:
        return dl.read_link(dl.Layout(self.root), self.root / "current")

    def previous(self) -> str | None:
        return dl.read_link(dl.Layout(self.root), self.root / "previous")

    def log_events(self) -> list[dict]:
        path = self.root / "shared" / "state" / "deploy-log.jsonl"
        return [json.loads(line) for line in path.read_text().splitlines()] if path.exists() else []

    def record_rehearsal(self, revision: str | None = "bbb222") -> None:
        """Kept for older scenarios: a standalone restore-check record. It no
        longer authorizes anything (deploy restore-checks its own backup)."""
        import deploy_db as ddb
        report = ddb.RestoreReport("f" * 64, revision, True, [])
        ddb.record_rehearsal(dl.Layout(self.root), lambda: NOW, report, "ok")

    def evidence_dirs(self) -> list[Path]:
        root = self.root / "shared" / "state" / "deployments"
        return sorted(root.iterdir()) if root.exists() else []

    def evidence(self, name: str, index: int = -1) -> dict:
        return json.loads((self.evidence_dirs()[index] / name).read_text())


def ledger_with(**extra) -> str:
    entries = {**LEDGER["revisions"], **{rev: {"class": cls, "note": "test"} for rev, cls in extra.items()}}
    return json.dumps({"schema_version": 1, "revisions": entries})


def migration_files(rev: str, down: str, cls: str) -> dict[str, str]:
    return {f"backend/alembic/versions/{rev}_new.py": migration(rev, down), "backend/ops/migration-classes.json": ledger_with(**{rev: cls})}
